apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pyapi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/use-http2: "true"
    external-dns.alpha.kubernetes.io/hostname: "pyapi.svc.${INGRESS_ZONE}"
    external-dns.alpha.kubernetes.io/target: "${INGRESS_LB_HOSTNAME}"

spec:
  tls:
  - hosts:
    - "pyapi.svc.${INGRESS_ZONE}"
    secretName: pyapi-ingress-tls
  rules:
  - host: "pyapi.svc.${INGRESS_ZONE}"
    http:
      paths:
      - path: /
        backend:
          serviceName: pyapi
          servicePort: 80
  }
