#!/usr/bin/env ruby

require 'pathname'

orbital_prefix = Pathname.new(__FILE__).realpath.parent.parent.expand_path

unless (orbital_prefix + '.git').directory?
  $stderr.puts "orbital is not a git worktree!"
  Kernel.exit 1
end

Dir.chdir(orbital_prefix.to_s)

on_branch = `git branch --show-current`.strip

unless on_branch == 'master'
  $stderr.puts "orbital worktree not on master"
  Kernel.exit 1
end

unless `git status --porcelain`.strip.empty?
  $stderr.puts "orbital worktree is dirty"
  Kernel.exit 1
end

system('git', 'fetch', 'origin')
system('git', 'reset', '--hard', 'origin/master')
