#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'rubygems'

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)
require 'bundler/setup'

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) unless $:.include?(lib_path)

require 'orbital/cli'

# require_relative '../lib/orbital/converger'

# Rake.application = Orbital::Converger.new
# Rake.application.run

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Orbital::CLI.start
rescue Orbital::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
